services:
  chat-be-1:
    image: anshulmalokar/chat-be:v1
    container_name: chat-be-1
    ports:
      - 3002:3002
    networks:
      - chat-ne
  chat-be-2:
    image: anshulmalokar/chat-be:v1
    container_name: chat-be-2
    ports:
      - 3003:3002
    networks:
      - chat-ne
  auth-auth-1:
    image: anshulmalokar/chat-auth:v1
    container_name: chat-auth-1
    ports:
      - 3005:3005
    networks:
      - chat-ne
  chat-fe-1:
    image: anshulmalokar/chat-fe:v1
    container_name: chat-fe-1
    ports:
      - 3000:3000
    depends_on:
      - chat-be-1
    networks:
      - chat-ne
  chat-fe-2:
    image: anshulmalokar/chat-fe:v2
    container_name: chat-fe-2
    ports:
      - 3001:3000
    depends_on:
      - chat-be-2
    networks:
      - chat-ne
networks:
  chat-ne:
    driver: bridge
    